### ISSUE TITLE
Dragger tracker background

### ISSUE THREAD

**Issue by DevoidCoding** [DominikSerafin/vuebar#25]
First of all, thank you for that amazing directive, it's awesome and marry well with my design !

I'm here to ask if it's possible to improve the actual behavior, and put a background behind de dragger, something like this : http://i.imgur.com/1FwzGi4.png

**Comment by DominikSerafin** [comment]
Hey @DevoidCoding it will be introduced in the 2.0 version of Vuebar (https://github.com/DominikSerafin/vuebar/projects/1). 

For now, as a workaround you can use maybe pseudo elements (::before/::after) to add that background on Vuebar `el1`.

**Comment by lethak** [comment]
@DevoidCoding I've done it with

```css
.vb::after {
    background-color: rgba(0, 0 , 0, .15);
    position: absolute;
    top:0;
    right:0;
    width: 7px;
    height: 100%;
    content: "";
    margin-right: 5px;
  }
```
