### ISSUE TITLE
dragger size when dragging is not customizable

### ISSUE THREAD

**Issue by lethak** [DominikSerafin/vuebar#38]
Hi,

How should I proceed if I never want dragger to change in width ?

I think it is not possible right now because of this, but it seems is more complicated than just commenting it.

```js
state.el2.style.width = 'calc(100% + ' + elNativeScrollbarWidth + 'px)';
```

**Comment by lethak** [comment]
Alright, I managed to do it somehow with: 

```css
.vb-dragger > .vb-dragger-styler {
width: 7px;
}
```
