### ISSUE TITLE
2 scrollers appear

### ISSUE THREAD

**Issue by trandaison** [DominikSerafin/vuebar#55]
When using the trackpad, there're 2 scrollers. This doesn't happen when I plug a mouse.

!![](https://media.giphy.com/media/KWQINVQd3vKr0GuIuZ/giphy.gif)

Here're my HTML and CSS:
```html
<div class="vuebar-element">
  <div>
    <!-- content here -->
  </div>
</div>
```
```css
  .vuebar-element {
    height: 250px;
    width: 100%;
  }

  .vb > .vb-dragger {
      z-index: 5;
      width: 12px;
      right: 0;
  }

  .vb > .vb-dragger > .vb-dragger-styler {
      -webkit-backface-visibility: hidden;
      backface-visibility: hidden;
      -webkit-transform: rotate3d(0,0,0,0);
      transform: rotate3d(0,0,0,0);
      -webkit-transition:
          background-color 100ms ease-out,
          margin 100ms ease-out,
          height 100ms ease-out;
      transition:
          background-color 100ms ease-out,
          margin 100ms ease-out,
          height 100ms ease-out;
      background-color: rgba(156, 39, 176, .0);
      margin: 5px 5px 5px 0;
      border-radius: 20px;
      height: calc(100% - 10px);
      display: block;
  }

  .vb.vb-scrolling-phantom > .vb-dragger > .vb-dragger-styler {
      background-color: rgba(156, 39, 176, .3);
  }

  .vb > .vb-dragger:hover > .vb-dragger-styler {
      background-color: rgba(156, 39, 176, .5);
      margin: 0px;
      height: 100%;
  }

  .vb.vb-dragging > .vb-dragger > .vb-dragger-styler {
      background-color: rgba(156, 39, 176, .5);
      margin: 0px;
      height: 100%;
  }

  .vb.vb-dragging-phantom > .vb-dragger > .vb-dragger-styler {
      background-color: rgba(156, 39, 176, .5);
  }

  .vuebar-element:hover {
    .vb-dragger-styler {
        background-color: rgba(156, 39, 176, .3);
    }
  }
```

**Comment by acupofspirt** [comment]
```css
<style>
  ::-webkit-scrollbar {
    display: none;
  }
</style>
```

**Comment by goors** [comment]
same here

**Comment by trandaison** [comment]
Hi @DominikSerafin,

This appear sometimes, and on some pc.
Suppose I can provide on jsfiddle, it doesn't make sure that this will happen on your browser 😂

**Comment by DominikSerafin** [comment]
@trandaison minimal repro on jsfiddle would be awesome. On which OSes/browsers does it happen?

**Comment by williamabbott** [comment]
![image](https://user-images.githubusercontent.com/5918271/53185065-8de3e980-35fe-11e9-80ce-0d7d22fb656b.png)

MBP 12, latest stable chrome, touchpad scrolling

**Comment by DominikSerafin** [comment]
Hey @williamabbott thanks for the image and info. GGather uses older version of Vuebar (0.0.18), didn't have yet chance to update. Have you seen this behavior with the newer versions of Vuebar?

**Comment by williamabbott** [comment]
Oh ok, no I haven't even used it yet. This was the first hurdle.




Sent from mobile







On Thu, Feb 21, 2019 at 7:00 PM +0100, "Dominik Serafin" <notifications@github.com> wrote:












Hey @williamabbott thanks for the image and info. GGather uses older version of Vuebar (0.0.18), didn't have yet chance to update. Have you seen this behavior with the newer versions of Vuebar?

**Comment by s0updev** [comment]
Got the same problem but with a mouse in latest Chrome\Opera on MacOS, as the tester reported.
And the text inside the container was moved when the second scrollbar appeared.

Vuebar version is 0.0.20

It helped:
```css
.vb > .vb-content::-webkit-scrollbar {
    -webkit-appearance: none;
}
```
